name: Build

on:
  push:
    branches-ignore:
      - main
  workflow_call:
    inputs:
      artifacts:
        required: false
        type: boolean
        default: false
        description: upload artifacts or not

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      id-token: write # to request JWT from GitHub OIDC provider
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: agilecustoms/setup-maven-codeartifact@v1
        with:
          aws-account: 123456789012
          aws-region: 'us-east-1'
          aws-role: 'ci/builder'
          aws-codeartifact-domain: agilecustoms
          java-version: '23'
          java-distribution: 'corretto'

      - name: Maven build
        run: mvn --no-transfer-progress verify

      - name: Upload artifacts
        if: ${{ inputs.artifacts }}
        uses: actions/upload-artifact@v4
        with:
          path: target/app.jar
          name: target #  so later on the download action will create <repo-root>/target/ folder
