name: Dev Release

on:
  workflow_dispatch:

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      artifacts: true
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  Release: # upload in S3 w/o version, just git hash
    needs: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Release
        uses: agilecustoms/gha-release@main
        with:
          dev-release: true

      - name: Summary
        run: echo "### Uploaded '$GITHUB_REF_NAME' to S3 :white_check_mark:" >> $GITHUB_STEP_SUMMARY
